"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "./components/navbar/navbar";
import { Provider } from "react-redux";
import store from "./store";
import { useEffect } from "react";
import { loadUser } from "@/features/auth/authSlice";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>)  {
  useEffect(() => {
    store.dispatch(loadUser())
  }, [])
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
        <NavigationBar />

        {children}
        </Provider>
      </body>
    </html>
  );
}
